import "~/styles/globals.css";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/header";
import { Toaster } from "~/components/ui/sonner";
import Footer from "./_components/footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <TRPCReactProvider>
            <Header/>
            {children}
            <Footer/>
            <Toaster/>
            </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
